name: CI

on:
  pull_request:
    branches:
      - prod
      - staging
      - dev
  push:
    branches:
      - feat/*
      - fix/*
      - chore/*

jobs:
  build:
    if: contains(fromJson('["pull_request"]'), github.event_name)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install package dependencies
        run: npm install

      - name: Create test build
        run: npm run build

  notify_slack:
    runs-on: ubuntu-latest
    steps:
      # IS A PUSH
      - if: contains(fromJson('["push"]'), github.event_name)
        uses: rtCamp/action-slack-notify
        env:
          SLACK_CHANNEL: develop_tracker
          SLACK_TITLE: Heyy! We've new push 🚀🚀🚀
          SLACK_USERNAME: (CI) Tracker
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL_TRACKER}}
          SLACK_MESSAGE: Changes into ${{github.ref_name}}

      # IS A PULL REQUEST
      - if: contains(fromJson('["pull_request"]'), github.event_name)
        uses: rtCamp/action-slack-notify
