name: deploy

on:
  push:
    branches:
      - fix/*

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to staging server"
    environment:
      name: staging
      url: https://staging.example.com
