name: Notifier

on:
  pull_request:
    branches: [ dev ]

jobs:

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: dev_bot
        SLACK_TITLE: New PR to dev
        SLACK_USERNAME: Bot CI - DEV
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        # SLACK_MESSAGE: "New PR to dev."