name: Notifier

on:
  pull_request:
    branches: [ dev ]

jobs:

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: bot_dev
        SLACK_TITLE: "New PR"
        SLACK_USERNAME: CI
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "Starting deploy 🚀🚀🚀"
