name: Notifier

on:
  push:
    branches: [ main, dev, feat/* ]
  pull_request:
    branches: [ main, dev, feat/* ]

jobs:

  messageSlack:
    runs-on: ubuntu-latest
    steps:
    - name: Notification Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: dev_bot
        SLACK_TITLE: Post Title
        SLACK_USERNAME: Bot CI
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: "This is your custom message."